"""Summarize retained contact histories and plot the actual driven operation.

No solver is launched. Failed runs stay failed; holding forces use reactions,
including stationary plateaus rather than motion-force summaries alone.
"""
import argparse
import json
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT=Path(__file__).resolve().parent
STAGES=(('close',0,.3),('press',.3,.45),('initial_lift',.45,.55),
        ('withdraw',.55,.65),('finish_lift',.65,1))

def summarize(labels):
    summary={}
    fig,axes=plt.subplots(1,4,figsize=(16,4))
    for label in labels:
        r=json.loads((ROOT/'notes/analysis'/label/'result.json').read_text())
        case=json.loads((ROOT/'notes/analysis'/label/'case.json').read_text())
        setup=dict(mesh_mm=case['parts'][0]['mesh_size_mm'],
            increment=case['max_increment'],penalty_N_mm3=case['contacts'][0]['penalty_N_mm3'],
            discretization=case['contacts'][0]['discretization'])
        h=r['history']
        if not h:
            summary[label]=dict(status=r['status'],completed=r['completed'],setup=setup,errors=r['errors'],history_frames=0)
            continue
        stages={}
        for name,lo,hi in STAGES:
            rows=[v for v in h if lo<v['load_fraction']<=hi+1e-9]
            stages[name]=dict(peak_lid_axis_force_N=max(abs(v['reactions_N']['lid'][2]) for v in rows),
                peak_press_axis_force_N=max(abs(v['reactions_N']['pinch'][1]) for v in rows),
                peak_strain=max(v['max_abs_principal_strain'] for v in rows),
                peak_penetration_mm=max(v['max_penetration_mm'] for v in rows))
        end=h[-1]['observations']['free_tab']
        closed=min(h,key=lambda v:abs(v['load_fraction']-.3))
        envelope=dict(inward_mm=max(-v['observations']['free_tab']['min_mm'][1] for v in h),
            axial_mm=max(abs(v['observations']['free_tab'][k][0]) for v in h for k in ('min_mm','max_mm')),
            vertical_min_mm=min(v['observations']['free_tab']['min_mm'][2] for v in h),
            vertical_max_mm=max(v['observations']['free_tab']['max_mm'][2] for v in h))
        recovery=max(abs(a) for k in ('min_mm','max_mm') for a in end[k])
        m=r['metrics']
        summary[label]=dict(status=r['status'],completed=r['completed'],setup=setup,stages=stages,
            peak_strain=m['max_abs_principal_strain'],peak_strain_location_mm=m['max_strain_element_centroid_mm'],
            peak_penetration_mm=m['max_penetration_mm'],force_balance_relative=m['max_force_balance_relative'],
            free_tab_envelope=envelope,return_error_mm=recovery,
            closed_contact_points=closed['contact_points'],end_contact_points=h[-1]['contact_points'],
            screens=dict(strain=m['max_abs_principal_strain']<=.015,
                penetration=m['max_penetration_mm']<=.02,force_balance=m['max_force_balance_relative']<.01,
                approximate_pair_closing_force=2*stages['close']['peak_lid_axis_force_N']<20,
                approximate_pair_opening_force=2*stages['finish_lift']['peak_lid_axis_force_N']<20,
                free_tab_clearance_envelope=(envelope['inward_mm']<2.2 and envelope['axial_mm']<.2
                    and envelope['vertical_min_mm']>-.3 and envelope['vertical_max_mm']<.9),
                elastic_recovery=recovery<1e-4))
        t=[v['load_fraction'] for v in h]
        for ax,values in zip(axes,([v['reactions_N']['lid'][2] for v in h],
                                  [-v['reactions_N']['pinch'][1] for v in h],
                                  [-v['observations']['head']['mean_mm'][1] for v in h],
                                  [100*v['max_abs_principal_strain'] for v in h])):
            ax.plot(t,values,label=f"{label} ({r['status']})")
    for ax,title,unit in zip(axes,('Lid axis reaction, one snap','Press/hold reaction, one pad',
                                 'Mean head inward movement','Peak absolute principal strain'),('N','N','mm','%')):
        ax.set(title=title,xlabel='Normalized operation progress',ylabel=unit)
        for boundary in (.3,.45,.55,.65): ax.axvline(boundary,color='.7',ls=':')
        ax.grid(alpha=.2)
    axes[0].legend(fontsize=7)
    axes[-1].axhline(1.5,color='red',ls='--')
    fig.suptitle('Conditional contact histories; failed runs are diagnostic only',fontsize=11)
    fig.tight_layout();fig.savefig(ROOT/'notes/contact_cycle.png',dpi=160);plt.close(fig)
    answer=dict(runs=summary,
        limits='Conditional local frictionless elastic fixture; approximate two-snap forces omit full shell compliance, '
               'asymmetry and friction. Recovery is elastic-model recovery, not plastic set, creep, fatigue or printed bonding.')
    (ROOT/'notes/numerical_summary.json').write_text(json.dumps(answer,indent=2)+'\n')
    lines=['# Generated contact study results', '',
        'Generated by `summarize_evidence.py` from retained native-run results. '
        'All forces are for one snap. Failed-quality histories are diagnostic, not qualified operating predictions.', '',
        '| Run | Mesh / increment | Contact / penalty N/mm³ | Status | Closing N | Final lift N | Peak strain % | Penetration mm |',
        '| --- | --- | --- | --- | --- | --- | --- | --- |']
    for label,s in summary.items():
        config=f"{s['setup']['mesh_mm']:g} / {s['setup']['increment']:g}"
        method='S2S' if s['setup']['discretization']=='surface_to_surface' else 'N2S'
        contact=f"{method} / {s['setup']['penalty_N_mm3']:g}"
        if 'stages' not in s:
            lines.append(f"| {label} | {config} | {contact} | {s['status']} | — | — | — | — |")
        else:
            lines.append(f"| {label} | {config} | {contact} | {s['status']} | "
                f"{s['stages']['close']['peak_lid_axis_force_N']:.3f} | "
                f"{s['stages']['finish_lift']['peak_lid_axis_force_N']:.3f} | "
                f"{100*s['peak_strain']:.3f} | {s['peak_penetration_mm']:.5f} |")
    lines+=['', 'Contact settings, stage forces, strain locations, deformation envelopes and recovery '
        'are in [the generated JSON](numerical_summary.json). Elastic return is not evidence of '
        'printed recovery, permanent set, creep or fatigue. Force balance alone does not establish '
        'contact accuracy. No failed run is promoted to a successful mechanism prediction.', '']
    (ROOT/'notes/numerical_results.md').write_text('\n'.join(lines))
    print(json.dumps(answer,indent=2))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('labels',nargs='+');a=p.parse_args();summarize(a.labels)
